priorities:
  fix: 0
  fix-py: 10
  fix-eol: 20
  fix-whitespace: 30
  check: 40

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args: ["--exit-non-zero-on-fix"]
        priority: fix
      - id: ruff-format
        priority: fix-py

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
        priority: check
      - id: check-merge-conflict
        priority: check
      - id: check-toml
        priority: check
      - id: check-yaml
        priority: check
      - id: debug-statements
        priority: check
      - id: end-of-file-fixer
        exclude: tests/fixtures/xfail/missing-newline-at-end-of-file.rst
        priority: fix-eol
      - id: trailing-whitespace
        exclude: tests/fixtures/xfail/trailing-whitespaces.rst
        priority: fix-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
      - id: check-dependabot
        priority: check
      - id: check-github-workflows
        priority: check

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        priority: check

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.26.1
    hooks:
      - id: zizmor
        priority: check

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.25.1
    hooks:
      - id: pyproject-fmt
        additional_dependencies: [tox]
        priority: fix

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
        priority: check

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.7.1
    hooks:
      - id: tox-ini-fmt
        priority: fix

  - repo: meta
    hooks:
      - id: check-hooks-apply
        priority: check
      - id: check-useless-excludes
        priority: check

ci:
  autoupdate_schedule: quarterly
