- id: sphinx-lint
  name: Sphinx Lint
  description: 'Searches for common typos in sphinx-flavored rst files.'
  types: [rst]
  # Defer to pre-commit on the best way to delegate resources across available cores
  args: [--jobs=1]
  entry: sphinx-lint
  language: python
